In [ ]:
pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib PyPDF2 pandas

Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.12/dist-packages (2.196.0)
Requirement already satisfied: google-auth-httplib2 in /usr/local/lib/python3.12/dist-packages (0.4.0)
Requirement already satisfied: google-auth-oauthlib in /usr/local/lib/python3.12/dist-packages (1.4.0)
Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.12/dist-packages (3.0.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (0.31.2)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (2.47.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (2.30.3)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (4.2.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib) (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.75.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.28.0)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.32.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (4.9.1)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.3.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.6.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2026.5.20)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
folder_path = "/content/drive/MyDrive/mestrado/artigos/"

Mounted at /content/drive

In [ ]:
import os
import re
import pandas as pd
from PyPDF2 import PdfReader

# ---------------------------------------
# CONFIGURAÇÕES
# ---------------------------------------
#SCOPES = ['https://www.googleapis.com/auth/drive.readonly']
#PDF_FOLDER_ID = 'PASTE_HERE_THE_FOLDER_ID'  # <-- ID da pasta no Google Drive

folder_path = "/content/drive/MyDrive/mestrado/artigos/"

terms = [
    "mutual information"
]

# Função para contar ocorrências
def count_terms(text, term):
    pattern = r'\b' + re.escape(term.lower()) + r'\b'
    return len(re.findall(pattern, text.lower()))

# Lista onde ficará o resultado consolidado
results = []

# Percorre todos os arquivos da pasta
for file in os.listdir(folder_path):
    if file.lower().endswith(".pdf"):
        pdf_path = os.path.join(folder_path, file)
        print(f"Lendo PDF: {file}")

        # Extrai texto do PDF
        reader = PdfReader(pdf_path)
        full_text = ""

        for page in reader.pages:
            full_text += page.extract_text() or ""

        # Conta os termos
        counts = {term: count_terms(full_text, term) for term in terms}
        counts["arquivo"] = file

        # Adiciona ao resultado
        results.append(counts)

# Gera DataFrame consolidado
df = pd.DataFrame(results)

# Exporta para Excel no Drive
output_path = "/content/drive/MyDrive/levantamento_temas_drive.xlsx"
df.to_excel(output_path, index=False)

print("Arquivo gerado em:", output_path)
df

Lendo PDF: 49 - Leveraging_Advanced_Machine_Learning_Algorithms_for_Loan_Repayment_Prediction (1).pdf
Lendo PDF: Aplicação de Técnicas de Otimização de Hiperparâmetros em Modelos de Machine Learning na Tarefa de Classificar Bons e Maus Clientes.pdf
Lendo PDF: 32 - Monetary_Loan_Eligibility_Prediction_using_Logistic_Regression_Algorithm.pdf
Lendo PDF: 54 - Optimizing_Creditworthiness_Assessment_Leveraging_PCA_and_ESVM_for_Improved_Credit_Score_Analysis.pdf
Lendo PDF: 51 - Predictive_Analytics_in_Credit_Scoring_Integrating_XG_Boost_and_Neural_Networks_for_Enhanced_Financial_Decision_Making.pdf
Lendo PDF: 53 - A_Voting_Ensemble_Learning_Model_for_Improved_Credit_Default_Risk_Prediction.pdf
Lendo PDF: 45 - Effective_Credit_Risk_Prediction_Using_Ensemble_Classifiers_With_Model_Explanation.pdf
Lendo PDF: 52 - Personal_Credit_Risk_Assessment_Based_on_Swarm_Intelligence_and_Random_Forest.pdf
Lendo PDF: Aplicacao_de_mineracao_de_dados_para_identificacao.pdf
Lendo PDF: 59 - Overcoming_Data_Limitations_in_Credit_Risk_Assessment_with_FinGPT-Generated_Synthetic_Data.pdf
Lendo PDF: 60 - DbISCDP_An_Empirical_Study_on_Distance-Based_Nearest_Neighbor_Approaches_for_Credit_Default_Prediction.pdf
Lendo PDF: 58 - Enhancing_Credit_Risk_Decision-Making_in_Supply_Chain_Finance_With_Interpretable_Machine_Learning_Model.pdf
Lendo PDF: 61 - Credit_Scoring_in_Africa_Employing_Logistic_Regression_on_Alternative_Data.pdf
Lendo PDF: 55 - Applying_Hybrid_Graph_Neural_Networks_to_Strengthen_Credit_Risk_Analysis.pdf
Lendo PDF: Modelo Preditivo para Avaliação de Crédito em Empréstimos.pdf
Lendo PDF: 43 - Finances_AI_Revolution_Transforming_Banking_and_Investments_for_Tomorrow.pdf
Lendo PDF: 26 - Comparative_study_of_Machine_Learning_Approaches_for_Loan_Approval_Prediction_in_financial_sector.pdf
Lendo PDF: Determinantes da inadimplência de pessoas físicas em.pdf
Lendo PDF: Loan_Default_Prediction_Using_Machine_Learning.pdf
Lendo PDF: 06 - Leveraging_Machine_Learning_and_Forecasting_Techniques_to_Enhance_Credit_Risk_Analysis_and_Prediction.pdf
Lendo PDF: 39 - Leveraging_Advanced_Machine_Learning_Algorithms_for_Loan_Repayment_Prediction.pdf
Lendo PDF: 56 - Machine_Learning_and_Deep_Learning_for_Loan_Prediction_in_Banking_Exploring_Ensemble_Methods_and_Data_Balancing.pdf
Lendo PDF: 30 - Predicting_Bank_Loan_Eligibility_with_Machine_Learning__A_Comparative_Study_of_Advanced_Algorithms.pdf
Lendo PDF: A_Credit_Risk_Assessment_System_for_Financial_Institutions_Utilizing_Deep_Learning.pdf
Lendo PDF: 42 - Bank_Loan_Prediction_System_Using_Machine_Learning_Models.pdf
Lendo PDF: 29 - Evaluating_Credit_Risk_in_Banking_using_AI-based_Algorithm_Optimization.pdf
Lendo PDF: 04 - Building_Ensemble_Models_for_Enhanced_Credit_Scoring_A_Case_Study_from_a_Bosnian_MicroFinancial_Institution.pdf
Lendo PDF: 17 - Customer_Credit_Risk_Application_and_Evaluation_of_Machine_Learning_and_Deep_Learning_Models.pdf
Lendo PDF: Prediction of bank credit worthiness through credit risk.pdf
Lendo PDF: Risk_Management_in_Financial_Institutions_with_Applied_Machine_Learning.pdf
Lendo PDF: 38 - Analyzing_Loan_Approvals_Through_Supervised_Machine_Learning_Techniques.pdf
Lendo PDF: 12 -Evolving Transparent Credit Risk Models A Symbolic Regression Approach Using Genetic Programming.pdf
Lendo PDF: 21 - AI-Driven_Credit_Scoring_and_Credit_Line_Solution_for_the_Unreserved_and_Self-Employed.pdf
Lendo PDF: 18 - Machine_Learning_Techniques_for_Credit_Scoring_in_Banking_with_Management_HR_and_Organizational_Key_Components.pdf
Lendo PDF: Applications of Artificial Intelligence in Sustainability Assessment and Risk Management in European Banking.pdf
Lendo PDF: Credit scoring using multi-task Siamese neural network for improving prediction performance and stability.pdf
Lendo PDF: Machine learning for enhanced credit risk assessment An empirical approach.pdf
Lendo PDF: 01 - Unlocking_Transparency_in_Credit_Scoring_Leveraging_XGBoost_with_XAI_for_Informed_Business_Decision-Making.pdf
Lendo PDF: 15 - A_Novel_Approach_for_Credit_Scoring_System_for_Loan_approval_using_Ensemble_learning_Algorithm.pdf
Lendo PDF: 07 - NATE Non-pArameTric approach for.pdf
Lendo PDF: 25 - Design_of_a_Personal_Credit_Risk_Prediction_Model_and_Legal_Prevention_of_Financial_Risks.pdf
Lendo PDF: 09-Enhancing credit risk prediction with hybrid deep learning and sand cat swarm feature selection.pdf
Lendo PDF: 11 - Credit Risk Prediction Using Machine Learning and Deep Learning A Study on Credit Card Customers.pdf
Lendo PDF: 20 - Loan_Default_Prediction_Based_on_Logistic_Regression_and_XGBoost_Modeling.pdf
Lendo PDF: Enhancing credit risk prediction with hybrid deep learning and sand cat swarm feature selection.pdf
Arquivo gerado em: /content/drive/MyDrive/levantamento_temas_drive.xlsx

    mutual information                                            arquivo
0                    0  49 - Leveraging_Advanced_Machine_Learning_Algo...
1                    0  Aplicação de Técnicas de Otimização de Hi...
2                    0  32 - Monetary_Loan_Eligibility_Prediction_usin...
3                    0  54 - Optimizing_Creditworthiness_Assessment_Le...
4                    0  51 - Predictive_Analytics_in_Credit_Scoring_In...
5                    0  53 - A_Voting_Ensemble_Learning_Model_for_Impr...
6                    0  45 - Effective_Credit_Risk_Prediction_Using_En...
7                    0  52 - Personal_Credit_Risk_Assessment_Based_on_...
8                    0  Aplicacao_de_mineracao_de_dados_para_identific...
9                    0  59 - Overcoming_Data_Limitations_in_Credit_Ris...
10                   0  60 - DbISCDP_An_Empirical_Study_on_Distance-Ba...
11                   0  58 - Enhancing_Credit_Risk_Decision-Making_in_...
12                   0  61 - Credit_Scoring_in_Africa_Employing_Logist...
13                   0  55 - Applying_Hybrid_Graph_Neural_Networks_to_...
14                   0  Modelo Preditivo para Avaliação de Crédito ...
15                   0  43 - Finances_AI_Revolution_Transforming_Banki...
16                   0  26 - Comparative_study_of_Machine_Learning_App...
17                   0  Determinantes da inadimplência de pessoas fí...
18                   0  Loan_Default_Prediction_Using_Machine_Learning...
19                   0  06 - Leveraging_Machine_Learning_and_Forecasti...
20                   0  39 - Leveraging_Advanced_Machine_Learning_Algo...
21                   0  56 - Machine_Learning_and_Deep_Learning_for_Lo...
22                   0  30 - Predicting_Bank_Loan_Eligibility_with_Mac...
23                   0  A_Credit_Risk_Assessment_System_for_Financial_...
24                   0  42 - Bank_Loan_Prediction_System_Using_Machine...
25                   0  29 - Evaluating_Credit_Risk_in_Banking_using_A...
26                   0  04 - Building_Ensemble_Models_for_Enhanced_Cre...
27                   0  17 - Customer_Credit_Risk_Application_and_Eval...
28                   0  Prediction of bank credit worthiness through c...
29                   0  Risk_Management_in_Financial_Institutions_with...
30                   0  38 - Analyzing_Loan_Approvals_Through_Supervis...
31                   0  12 -Evolving Transparent Credit Risk Models A ...
32                   0  21 - AI-Driven_Credit_Scoring_and_Credit_Line_...
33                   0  18 - Machine_Learning_Techniques_for_Credit_Sc...
34                   0  Applications of Artificial Intelligence in Sus...
35                   0  Credit scoring using multi-task Siamese neural...
36                   0  Machine learning for enhanced credit risk asse...
37                   0  01 - Unlocking_Transparency_in_Credit_Scoring_...
38                   0  15 - A_Novel_Approach_for_Credit_Scoring_Syste...
39                   0          07 - NATE Non-pArameTric approach for.pdf
40                   0  25 - Design_of_a_Personal_Credit_Risk_Predicti...
41                   0  09-Enhancing credit risk prediction with hybri...
42                   0  11 - Credit Risk Prediction Using Machine Lear...
43                   0  20 - Loan_Default_Prediction_Based_on_Logistic...
44                   0  Enhancing credit risk prediction with hybrid d...

In [ ]:
df.to_excel("levantamento.xlsx")

In [ ]:
pip install pydrive

Collecting pydrive
  Downloading PyDrive-1.3.1.tar.gz (987 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 987.4/987.4 kB 14.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: google-api-python-client>=1.2 in /usr/local/lib/python3.12/dist-packages (from pydrive) (2.196.0)
Requirement already satisfied: oauth2client>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pydrive) (4.1.3)
Requirement already satisfied: PyYAML>=3.0 in /usr/local/lib/python3.12/dist-packages (from pydrive) (6.0.3)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.2->pydrive) (0.31.2)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.2->pydrive) (2.47.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.2->pydrive) (0.4.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.2->pydrive) (2.30.3)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.2->pydrive) (4.2.0)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=4.0.0->pydrive) (0.6.3)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=4.0.0->pydrive) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=4.0.0->pydrive) (4.9.1)
Requirement already satisfied: six>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=4.0.0->pydrive) (1.17.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.2->pydrive) (1.75.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.2->pydrive) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.2->pydrive) (1.28.0)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.2->pydrive) (2.32.4)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client>=1.2->pydrive) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.2->pydrive) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.2->pydrive) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.2->pydrive) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.2->pydrive) (2026.5.20)
Building wheels for collected packages: pydrive
  Building wheel for pydrive (setup.py) ... done
  Created wheel for pydrive: filename=PyDrive-1.3.1-py3-none-any.whl size=27433 sha256=1a02cb1afd98497495fe2cbbe993cc63ef84fde7b1ef742ddaad3fc3e15d5308
  Stored in directory: /root/.cache/pip/wheels/6c/10/da/a5b513f5b3916fc391c20ee7b4633e5cf3396d570cdd74970f
Successfully built pydrive
Installing collected packages: pydrive
Successfully installed pydrive-1.3.1

In [ ]:
pip install pdfplumber

Collecting pdfplumber
  Downloading pdfplumber-0.11.9-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.1 MB/s eta 0:00:00
Collecting pdfminer.six==20251230 (from pdfplumber)
  Downloading pdfminer_six-20251230-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-5.9.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.4/68.4 kB 4.7 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (3.4.7)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (48.0.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (3.0)
Downloading pdfplumber-0.11.9-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 4.2 MB/s eta 0:00:00
Downloading pdfminer_six-20251230-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 35.9 MB/s eta 0:00:00
Downloading pypdfium2-5.9.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 53.8 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20251230 pdfplumber-0.11.9 pypdfium2-5.9.0

In [ ]:
import os
import re
import pandas as pd
from PyPDF2 import PdfReader

# ---------------------------------------
# CONFIGURAÇÕES
# ---------------------------------------
folder_path = "/content/drive/MyDrive/mestrado/artigos/"  # <-- mesma lógica que já funciona

# Regex para achar anos entre 1900 e 2099
year_pattern = r"\b(19[0-9]{2}|20[0-9]{2})\b"

# Função para identificar o ano mais provável
def extract_year(text):
    years = re.findall(year_pattern, text)
    if not years:
        return None
    # Retorna o ano mais frequente no PDF
    return max(set(years), key=years.count)

# Lista com os resultados
results = []

# Percorre todos os PDFs da pasta
for file in os.listdir(folder_path):
    if file.lower().endswith(".pdf"):
        pdf_path = os.path.join(folder_path, file)
        print(f"Lendo PDF: {file}")

        # Extrai texto
        reader = PdfReader(pdf_path)
        full_text = ""

        for page in reader.pages:
            full_text += page.extract_text() or ""

        # Extrai o ano
        year = extract_year(full_text)

        results.append({
            "arquivo": file,
            "ano_publicacao": year
        })

# Converte para DataFrame
df = pd.DataFrame(results)

# Exporta para Excel
output_path = "/content/drive/MyDrive/levantamento_anos_publicacao.xlsx"
df.to_excel(output_path, index=False)

print("Arquivo gerado em:", output_path)
df

Lendo PDF: 49 - Leveraging_Advanced_Machine_Learning_Algorithms_for_Loan_Repayment_Prediction (1).pdf
Lendo PDF: Aplicação de Técnicas de Otimização de Hiperparâmetros em Modelos de Machine Learning na Tarefa de Classificar Bons e Maus Clientes.pdf
Lendo PDF: 32 - Monetary_Loan_Eligibility_Prediction_using_Logistic_Regression_Algorithm.pdf
Lendo PDF: 54 - Optimizing_Creditworthiness_Assessment_Leveraging_PCA_and_ESVM_for_Improved_Credit_Score_Analysis.pdf
Lendo PDF: 51 - Predictive_Analytics_in_Credit_Scoring_Integrating_XG_Boost_and_Neural_Networks_for_Enhanced_Financial_Decision_Making.pdf
Lendo PDF: 53 - A_Voting_Ensemble_Learning_Model_for_Improved_Credit_Default_Risk_Prediction.pdf
Lendo PDF: 45 - Effective_Credit_Risk_Prediction_Using_Ensemble_Classifiers_With_Model_Explanation.pdf
Lendo PDF: 52 - Personal_Credit_Risk_Assessment_Based_on_Swarm_Intelligence_and_Random_Forest.pdf
Lendo PDF: Aplicacao_de_mineracao_de_dados_para_identificacao.pdf
Lendo PDF: 59 - Overcoming_Data_Limitations_in_Credit_Risk_Assessment_with_FinGPT-Generated_Synthetic_Data.pdf
Lendo PDF: 60 - DbISCDP_An_Empirical_Study_on_Distance-Based_Nearest_Neighbor_Approaches_for_Credit_Default_Prediction.pdf
Lendo PDF: 58 - Enhancing_Credit_Risk_Decision-Making_in_Supply_Chain_Finance_With_Interpretable_Machine_Learning_Model.pdf
Lendo PDF: 61 - Credit_Scoring_in_Africa_Employing_Logistic_Regression_on_Alternative_Data.pdf
Lendo PDF: 55 - Applying_Hybrid_Graph_Neural_Networks_to_Strengthen_Credit_Risk_Analysis.pdf
Lendo PDF: Modelo Preditivo para Avaliação de Crédito em Empréstimos.pdf
Lendo PDF: 43 - Finances_AI_Revolution_Transforming_Banking_and_Investments_for_Tomorrow.pdf
Lendo PDF: 26 - Comparative_study_of_Machine_Learning_Approaches_for_Loan_Approval_Prediction_in_financial_sector.pdf
Lendo PDF: Determinantes da inadimplência de pessoas físicas em.pdf
Lendo PDF: Loan_Default_Prediction_Using_Machine_Learning.pdf
Lendo PDF: 06 - Leveraging_Machine_Learning_and_Forecasting_Techniques_to_Enhance_Credit_Risk_Analysis_and_Prediction.pdf
Lendo PDF: 39 - Leveraging_Advanced_Machine_Learning_Algorithms_for_Loan_Repayment_Prediction.pdf
Lendo PDF: 56 - Machine_Learning_and_Deep_Learning_for_Loan_Prediction_in_Banking_Exploring_Ensemble_Methods_and_Data_Balancing.pdf
Lendo PDF: 30 - Predicting_Bank_Loan_Eligibility_with_Machine_Learning__A_Comparative_Study_of_Advanced_Algorithms.pdf
Lendo PDF: A_Credit_Risk_Assessment_System_for_Financial_Institutions_Utilizing_Deep_Learning.pdf
Lendo PDF: 42 - Bank_Loan_Prediction_System_Using_Machine_Learning_Models.pdf
Lendo PDF: 29 - Evaluating_Credit_Risk_in_Banking_using_AI-based_Algorithm_Optimization.pdf
Lendo PDF: 04 - Building_Ensemble_Models_for_Enhanced_Credit_Scoring_A_Case_Study_from_a_Bosnian_MicroFinancial_Institution.pdf
Lendo PDF: 17 - Customer_Credit_Risk_Application_and_Evaluation_of_Machine_Learning_and_Deep_Learning_Models.pdf
Lendo PDF: Prediction of bank credit worthiness through credit risk.pdf
Lendo PDF: Risk_Management_in_Financial_Institutions_with_Applied_Machine_Learning.pdf
Lendo PDF: 38 - Analyzing_Loan_Approvals_Through_Supervised_Machine_Learning_Techniques.pdf
Lendo PDF: 12 -Evolving Transparent Credit Risk Models A Symbolic Regression Approach Using Genetic Programming.pdf
Lendo PDF: 21 - AI-Driven_Credit_Scoring_and_Credit_Line_Solution_for_the_Unreserved_and_Self-Employed.pdf
Lendo PDF: 18 - Machine_Learning_Techniques_for_Credit_Scoring_in_Banking_with_Management_HR_and_Organizational_Key_Components.pdf
Lendo PDF: Applications of Artificial Intelligence in Sustainability Assessment and Risk Management in European Banking.pdf
Lendo PDF: Credit scoring using multi-task Siamese neural network for improving prediction performance and stability.pdf
Lendo PDF: Machine learning for enhanced credit risk assessment An empirical approach.pdf
Lendo PDF: 01 - Unlocking_Transparency_in_Credit_Scoring_Leveraging_XGBoost_with_XAI_for_Informed_Business_Decision-Making.pdf
Lendo PDF: 15 - A_Novel_Approach_for_Credit_Scoring_System_for_Loan_approval_using_Ensemble_learning_Algorithm.pdf
Lendo PDF: 07 - NATE Non-pArameTric approach for.pdf
Lendo PDF: 25 - Design_of_a_Personal_Credit_Risk_Prediction_Model_and_Legal_Prevention_of_Financial_Risks.pdf
Lendo PDF: 09-Enhancing credit risk prediction with hybrid deep learning and sand cat swarm feature selection.pdf
Lendo PDF: 11 - Credit Risk Prediction Using Machine Learning and Deep Learning A Study on Credit Card Customers.pdf
Lendo PDF: 20 - Loan_Default_Prediction_Based_on_Logistic_Regression_and_XGBoost_Modeling.pdf
Lendo PDF: Enhancing credit risk prediction with hybrid deep learning and sand cat swarm feature selection.pdf
Arquivo gerado em: /content/drive/MyDrive/levantamento_anos_publicacao.xlsx

                                              arquivo ano_publicacao
0   49 - Leveraging_Advanced_Machine_Learning_Algo...           2024
1   Aplicação de Técnicas de Otimização de Hi...           2023
2   32 - Monetary_Loan_Eligibility_Prediction_usin...           2022
3   54 - Optimizing_Creditworthiness_Assessment_Le...           2025
4   51 - Predictive_Analytics_in_Credit_Scoring_In...           2020
5   53 - A_Voting_Ensemble_Learning_Model_for_Impr...           2024
6   45 - Effective_Credit_Risk_Prediction_Using_En...           2024
7   52 - Personal_Credit_Risk_Assessment_Based_on_...           2025
8   Aplicacao_de_mineracao_de_dados_para_identific...           2023
9   59 - Overcoming_Data_Limitations_in_Credit_Ris...           2025
10  60 - DbISCDP_An_Empirical_Study_on_Distance-Ba...           2025
11  58 - Enhancing_Credit_Risk_Decision-Making_in_...           2022
12  61 - Credit_Scoring_in_Africa_Employing_Logist...           2020
13  55 - Applying_Hybrid_Graph_Neural_Networks_to_...           2024
14  Modelo Preditivo para Avaliação de Crédito ...           2019
15  43 - Finances_AI_Revolution_Transforming_Banki...           2024
16  26 - Comparative_study_of_Machine_Learning_App...           2022
17  Determinantes da inadimplência de pessoas fí...           2018
18  Loan_Default_Prediction_Using_Machine_Learning...           2023
19  06 - Leveraging_Machine_Learning_and_Forecasti...           2025
20  39 - Leveraging_Advanced_Machine_Learning_Algo...           2024
21  56 - Machine_Learning_and_Deep_Learning_for_Lo...           2021
22  30 - Predicting_Bank_Loan_Eligibility_with_Mac...           2024
23  A_Credit_Risk_Assessment_System_for_Financial_...           2021
24  42 - Bank_Loan_Prediction_System_Using_Machine...           2024
25  29 - Evaluating_Credit_Risk_in_Banking_using_A...           2024
26  04 - Building_Ensemble_Models_for_Enhanced_Cre...           2022
27  17 - Customer_Credit_Risk_Application_and_Eval...           2020
28  Prediction of bank credit worthiness through c...           2021
29  Risk_Management_in_Financial_Institutions_with...           2024
30  38 - Analyzing_Loan_Approvals_Through_Supervis...           2024
31  12 -Evolving Transparent Credit Risk Models A ...           2024
32  21 - AI-Driven_Credit_Scoring_and_Credit_Line_...           2025
33  18 - Machine_Learning_Techniques_for_Credit_Sc...           2022
34  Applications of Artificial Intelligence in Sus...           2020
35  Credit scoring using multi-task Siamese neural...           2019
36  Machine learning for enhanced credit risk asse...           2023
37  01 - Unlocking_Transparency_in_Credit_Scoring_...           2021
38  15 - A_Novel_Approach_for_Credit_Scoring_Syste...           2023
39          07 - NATE Non-pArameTric approach for.pdf           None
40  25 - Design_of_a_Personal_Credit_Risk_Predicti...           2022
41  09-Enhancing credit risk prediction with hybri...           2024
42  11 - Credit Risk Prediction Using Machine Lear...           2024
43  20 - Loan_Default_Prediction_Based_on_Logistic...           2024
44  Enhancing credit risk prediction with hybrid d...           2024

In [ ]:
df.to_excel('atigos_anos.xlsx')

In [ ]:
!cat /proc/cpuinfo | grep "model name" | head -1

model name	: Intel(R) Xeon(R) CPU @ 2.20GHz

In [ ]:
!lscpu

Architecture:                x86_64
  CPU op-mode(s):            32-bit, 64-bit
  Address sizes:             46 bits physical, 48 bits virtual
  Byte Order:                Little Endian
CPU(s):                      2
  On-line CPU(s) list:       0,1
Vendor ID:                   GenuineIntel
  Model name:                Intel(R) Xeon(R) CPU @ 2.20GHz
    CPU family:              6
    Model:                   79
    Thread(s) per core:      2
    Core(s) per socket:      1
    Socket(s):               1
    Stepping:                0
    BogoMIPS:                4399.99
    Flags:                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pg
                             e mca cmov pat pse36 clflush mmx fxsr sse sse2 ss h
                             t syscall nx pdpe1gb rdtscp lm constant_tsc rep_goo
                             d nopl xtopology nonstop_tsc cpuid tsc_known_freq p
                             ni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2ap
                             ic movbe popcnt aes xsave avx f16c rdrand hyperviso
                             r lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp fs
                             gsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invp
                             cid rtm rdseed adx smap xsaveopt arat md_clear arch
                             _capabilities
Virtualization features:
  Hypervisor vendor:         KVM
  Virtualization type:       full
Caches (sum of all):
  L1d:                       32 KiB (1 instance)
  L1i:                       32 KiB (1 instance)
  L2:                        256 KiB (1 instance)
  L3:                        55 MiB (1 instance)
NUMA:
  NUMA node(s):              1
  NUMA node0 CPU(s):         0,1
Vulnerabilities:
  Gather data sampling:      Not affected
  Indirect target selection: Vulnerable
  Itlb multihit:             Not affected
  L1tf:                      Mitigation; PTE Inversion
  Mds:                       Vulnerable; SMT Host state unknown
  Meltdown:                  Vulnerable
  Mmio stale data:           Vulnerable
  Reg file data sampling:    Not affected
  Retbleed:                  Vulnerable
  Spec rstack overflow:      Not affected
  Spec store bypass:         Vulnerable
  Spectre v1:                Vulnerable: __user pointer sanitization and usercop
                             y barriers only; no swapgs barriers
  Spectre v2:                Vulnerable; IBPB: disabled; STIBP: disabled; PBRSB-
                             eIBRS: Not affected; BHI: Vulnerable
  Srbds:                     Not affected
  Tsa:                       Not affected
  Tsx async abort:           Vulnerable
  Vmscape:                   Not affected

In [ ]:
!cat /proc/meminfo | grep MemTotal

MemTotal:       13286944 kB

In [ ]:
!free -h

               total        used        free      shared  buff/cache   available
Mem:            12Gi       794Mi       8.9Gi       2.0Mi       3.0Gi        11Gi
Swap:             0B          0B          0B

In [ ]:
!python --version

Python 3.12.13

In [ ]:
import platform
import psutil

print("Sistema operacional:", platform.platform())
print("Processador:", platform.processor())
print("Núcleos:", psutil.cpu_count())
print("RAM (GB):", round(psutil.virtual_memory().total / (1024**3), 2))

Sistema operacional: Linux-6.6.122+-x86_64-with-glibc2.35
Processador: x86_64
Núcleos: 2
RAM (GB): 12.67

In [ ]:
import torch

print(torch.cuda.is_available())

False